#!/bin/sh

man=$(man -k . | dmenu -Y 37 -X 12 -W 800 -l 37 -i | awk '{print $1}') &&
	view=$(printf "Terminal\nPDF" | dmenu -Y 37 -X 12 -w 116 -l 2 -i) &&
	case $view in
	'PDF') man -Tpdf $man | zathura - ;;
	'Terminal') kitty -e man $man ;;
	esac
